production:
  host: localhost
  database: wordpress_fsa
  username: wp
  password: 'wp'
staging:
  host: localhost
  database: friendss_staging_wp
  username: friendss_stage_u
  password: '}eq*X*J==Uls'
local:
  host: localhost
  database: friendss_production_wp
  username: friendss_prod_u
  password: 'a%(tt1qW5;L#'
